image_alpha = 1

if (global.autostart) {
	image_index = 1
}

adjusting = false
goUp = true
alarmList = []

showDisplay = -1
frame = 0
shooting = false
page = 0
modifierTranslations = ["Time Waster", "Chonker", "Wheel", "We are running out of money to buy you all beans", "Scammed", "Legal Issues", "No House Insurance", "UltraScitzo", "Bruh you slow af", "Bruh you weak af", "They messed up my prescription", "Negative Reinforcement", "You play well, but can you tango with 2?", "Big and Burly", "Inflation", "Awful Game Design", "The Moon", "The Sun", "Death", "The Fool", "The Magician", "The High Priestess", "Empress", "Temperance", "Fortune Teller", "The Wheel of Fortune", "Judgement", "Strength", "The World", "The Tower"]
logbookEntries = ["Gunner", "Sniper", "Railgunner", "Evaporator", "Boomer", "Flamer", "Puncher", "Laser", "Cheerleader", "Moneymaker", "Spotter", "Booster", "Commander", "Hacker", "Rapper", "Debt Collector","Evil Girls United", "Normal Enemies", "Camo Enemies", "Solid Enemies", "Invisible Enemies", "Summoner Enemies", "Minibosses", "Bosses", "Normal", "Fast", "Tanky", "Fanky", "Camo", "Solid", "Gnormal", "Job Ross", "Necromancer", "Nicky", "SUPERHATEYOUGIRL", "Butter", "TF2 Spy", "Bob Crisscross", "Titanium", "Knormle", "Soldier", "Assassin", "Gauss Machine Gun", "Dissapator"]
enemyLogEndIndex = 39
logbookDesc = [
	//Towers Page 1
	{title : "Gunner", desc : "Cheap, simple tower with consistent damage. \n$150 \n1 Damage \n0.5 sec Cooldown \n250 range \nUpgrade costs $75 >> $125 >> $200 >> $550", sprite : tower0_spr, spriteShooting : towerShooting0_spr},
	{title : "Sniper", desc : "Slightly more expensive tower with high damage and lower firerate. \n$325 \n7 Damage \n2 sec Cooldown \n500 range \nAutomatic camo detection \nUpgrade costs $125 >> $200 >> $325 >> $850", sprite : tower1_spr, spriteShooting : towerShooting1_spr},
	{title : "Railgunner", desc : "Expensive tower with very low firerate and very high damage. \n$1000 \n75 Damage \n5 sec Cooldown \n550 range \n20 Pierce \nAutomatic camo detection \nUpgrade costs $500 >> $825 >> $1300 >> $4800", sprite : tower2_spr, spriteShooting : towerShooting2_spr},
	{title : "Evaporator", desc : "Boss killer tower with AOE damage at higher levels, highest damage. \n$3750 \n1000 Damage \n10 sec Cooldown \n400 range \nHas invisible detection \nUpgrade costs $1750 >> $2750 >> $4500 >> $14000", sprite : tower3_spr, spriteShooting : towerShooting3_spr},
	{title : "Boomer", desc : "Low cost, low damage AOE tower that deals better chip damage at later levels. \n$200 \n2 Damage \n1 sec Cooldown \n200 range \n10 Pierce \nCan hit solids \nUpgrade costs $100 >> $150 >> $275 >> $650", sprite : tower4_spr, spriteShooting : towerShooting4_spr},
	{title : "Flamer", desc : "Pricier tower that sets enemies on fire which turns them into sludge. \n$550 \n0.2 Damage \n0.5 sec Cooldown \n150 range \nCan hit solids \nSets enemies on fire that does 10 damage over 3.3 seconds \nUpgrade costs $275 >> $450 >> $725 >> $1500", sprite : tower5_spr, spriteShooting : towerShooting5_spr},
	{title : "Puncher", desc : "Pricier tower that hits multiple enemies with their swings for higher damage mutli target. \n$1000 \n5 Damage \n0.5 sec Cooldown \n5 Pierce \n100 range \nUpgrade costs $500 >> $825 >> $1325 >> $4250", sprite : tower6_spr, spriteShooting : towerShooting6_1_spr},
	{title : "Laser", desc : "Expensive tower that covers an entire line of the map to shred enemies. \n$5000 \n3 Damage \n0.2 sec Cooldown \n25 Pierce \nFires a continuous beam that doesn't rotate \nUpgrade costs $2500 >> $4150 >> $6500 >> $8000", sprite : tower7_spr},
	//Towers Page 2
	{title : "Cheerleader", desc : "Support tower that encourages others and boosts firerate. \n$850 \n10% firerate buff \nrange 300 \nUpgrade Costs $425 >> $700 >> $1125 >> $2000", sprite : tower8_spr},
	{title : "Moneymaker", desc : "Pricier support tower that makes good financial decisions during the round for money. \n$700 \n$100 per wave \nUpgrade Costs $350 >> $575 >> $925 >> $1800", sprite : tower9_spr},
	{title : "Spotter", desc : "Even pricier support tower that gives tips on the weak-points of enemies and tells other towers where to shoot. \n$1500 \nrange 450 \n+10% damage \n+15% range \nGives Camo Detection \nUpgrade Costs $1750 >> $2850 >> $3500 >> $5500", sprite : tower10_spr},
	{title : "Booster", desc : "Definitive support tower that increases the damage of other girls. \n$2400 \nrange 350 \nstarts with 40% damage boost ability that give to 1 tower in range \nUpgrade Costs $2000 >> $3250 >> $5350 >>$7000", sprite : tower11_spr},
	{title : "Commander", desc : "All-in-one tower that calls in strategic bomb placements according to their targeting. She also boosts the firerate of the other towers. \n$3500 \nMultiple aerial attacks every 600 or so frames which focus on a place on the path (each bomb does 50 damage). \nif set on strongest the bombs will all focus on one target \n+15% attack speed \nCamo and lead hitting \nUpgrade Costs $2000 >> $3250 >> $5250 >> $10000", sprite : tower12_spr},
	{title : "Hacker", desc : "Tower that gives a discount on upgrading girls. She also has multiple beams which can focus into one to shred a single target. \n$3500 \n5% discount \n2 beams that focus onto enemies (5 damage every 12 frames for 25 dps) \n450 range \nInvisible detection, lead detection, and camo detection \nUpgrade Costs $1875 >> $3125 >> $5000 >> $8000", sprite : tower13_spr, spriteShooting : towerShooting13_spr},
	{title : "Rapper", desc : "A tower similar to moneymaker that uses their piercing bars to beat up enemies. \n$1700 \nMakes $250 \nPuncher-esque attack every 0.2 seconds for 5 damage. \nInvisibility detection \nPierce 5 \nUpgrade Costs $1750 >> $2900 >> $4650 >> $10000", sprite : tower14_spr, spriteShooting : towerShooting14_spr},
	{title : "Debt Collector", desc : "A tower that can't be upgraded, but gets more powerful the more enemies they beat up. \n$800 \nLevels up at 25 enemies, 100 enemies, and 500 enemies. \nEach additional kill after 500 enemies gives an extra +0.2% damage \nUses a shotgun that shoots pellets 3 >> 5 >> 7 >> 10 with a 15 degree spread on each side \nDamage 2 >> 4 >> 10 >> 25 \nFirerate 60 >> 45 >>  >> 12 \nRange 250 >> 300 >> 450 >> 650 \nGives extra money from enemies. Bonus cash scales from: +0% >> +25% >> +50% >> +100% \nNo detections >> Camo detection>>camo + lead detection>>invisibility + camo + lead detection", sprite : tower15_spr, spriteShooting : towerShooting15_spr},
	//Enemies Page 1
	{title : "Evil Girls United", desc : "After the Spanish AIDS swept across most of the male population, two factions of girls were formed. While Girls United uses their organization to cure Spanish AIDS, Evil Girls United uses the unique secretions of infected men to clone the most devious of women, and give them wallets with money in them. \nEvery day, thousands of not very trustworthy women follow trails and pathways to hospitals to punch nurses. After that, the members of EGU go and find an occupation to pay rent. It's commonly deduced that if the Evil Girls were just told to not punch people, they would actually be much more appreciated workers. \nEvil Girls United spawns their enemies based on a points scale. The points increase with the waves (and with certain modifiers!), and are spent on more enemies. Enemies are also more or less likely to spawn depending on their value.", sprite : enemy34_spr},
	{title : "Normal Enemies", desc : "Enemies follow the path as normal, take 100% damage, and do not have any resistances.", sprite : enemy0_spr},
	{title : "Camo Enemies", desc : "Camo enemies can only be spotted by towers that have camo detection, however, if a camo enemy is caught in an explosion they will also take full damage from it", sprite : enemy4_spr},
	{title : "Solid Enemies", desc : "Solid enemies take -75% damage or only 1/4th the normal amount from regular towers, but any tower with the ability to pierce solids will do the full 100% damage.", sprite : enemy5_spr},
	{title : "Invisible Enemies", desc : "Invisible enemies can't be hit by towers with no detections. Towers with either camo or solid hitting do 25% damage to invisible enemies. Towers will both camo and solid htting do 50% damage, and towers with invisibility detection will always do 100% damage, no matter the other detections. Towers with only invisibility detection do not gain camo or solid hitting.", sprite : enemy9_spr},
	{title : "Summoner Enemies", desc : "Summoner enemies bring more trouble on the track. They can spawn crowds of enemies every few seconds (and when they die!), which could be big trouble if you don't deal with them soon enough.", sprite : enemy8_spr},
	{title : "Minibosses", desc : "Minibosses are enemies with much higher health than the others, acting as a check for your defenses. The average miniboss will have around five times more health than the enemies before it, making them quite threatening if you lack any single-target damage.", sprite : enemy7_spr},
	{title : "Bosses", desc : "Bosses are the last enemy to spawn in every stage, and the most dangerous. Each boss has its own unique traits, such as camo detection or lead detection. Typically, bosses will bear a resemblance to the enemies they spawn with, so measuring the power of a boss may lie in the power of the enemies. \nAll bosses increase in power with every stage that they arrive in.", sprite : enemy28_spr},
	//Enemies Page 2
	{title : "Normal", desc : "5 Health \n4 Speed \n20% More likely to spawn \nWeighed at 1 point \nSpawns on Wave 1 \nThe most simple girl. She likes eating plain rice and nutrient sticks.", sprite : enemy0_spr},
	{title : "Fast", desc : "4 Health \n6 Speed \n5% Less likely to spawn \nWeighed at 1 point \nSpawns on Wave 2 \nA fast girl. She likes rain and puddles.", sprite : enemy1_spr},
	{title : "Tanky", desc : "15 Health \n2 Speed \n5% More likely to spawn \nWeighed at 1 point \nSpawns on Wave 3 \nA tough girl. She enjoys forests and moss carpets.", sprite : enemy2_spr},
	{title : "Fanky", desc : "7 Health \n5 Speed \n10% More likely to spawn \nWeighed at 2.5 points \nSpawns on Wave 6 \nA well-rounded girl. She puts forks in outlets.", sprite : enemy3_spr},
	{title : "Camo", desc : "5 Health \n5 Speed \nCamo Enemy \nNormal spawn chance \nWeighed at 1.5 points \nSpawns on Wave 7 \nA sneaky girl. She likes ninjas and glass.", sprite : enemy4_spr},
	{title : "Solid", desc : "15 Health \n2 Speed \nSolid Enemy \nNormal spawn chance \nWeighed at 3 points \nSpawns on Wave 10 \nA very tough girl. She eats rocks.", sprite : enemy5_spr},
	{title : "Gnormal", desc : "12 Health \n4 Speed \n30% More likely to spawn \nWeighed at 3 points \nSpawns on Wave 11 \nA less simple girl. She hates groups and socializing", sprite : enemy6_spr},
	{title : "Job Ross", desc : "80 Health \n2 Speed \n20% Less likely to spawn \nWeighed at 10 points \nSpawns on Wave 13 \nAn artistic girl. She likes nature and forests.", sprite : enemy7_spr},
	//Enemies Page 3
	{title : "Necromancer", desc : "35 Health \n2 Speed \nSpawns Gnormals in groups of 4 every 5 seconds and upon death \n50% Less likely to spawn \nWeighed at 7 points \nSpawns on Wave 15 \nA novice witch. She likes purple and evil stuff.", sprite : enemy8_spr},
	{title : "Nicky", desc : "7 Health \n4 Speed \nInvisible Enemy \n10% Less likely to spawn \nWeighed at 5 points \nSpawns on Wave 16 \nA ninja girl. She hates being seen by others, so she makes herself more obvious by dressing as a ninja in the middle of winter.", sprite : enemy9_spr},
	{title : "SUPERHATEYOUGIRL", desc : "30 Health \n6 Speed \n20% More likely to spawn \nWeighed at 7 points \nSpawns on Wave 17 \nA very positive girl. She loves everything but expresses it in a different way.", sprite : enemy10_spr},
	{title : "Butter", desc : "20 Health \n12 Speed \n5% Less likely to spawn \nWeighed at 5 points \nSpawns on Wave 18 \nA very frightened girl. She likes microwaved food and energy drinks.", sprite : enemy11_spr},
	{title : "Spy", desc : "35 Health \n5 Speed \nCamo Enemy \n10% More likely to spawn \nWeighed at 10 points \nSpawns on Wave 19 \nNot the Gunner. She likes fortresses and silent men, like Joe.", sprite : enemy12_spr},
	{title : "Bob Crisscross", desc : "200 Health \n3 Speed \n15% Less likely to spawn \nWeighed at 20 points \nSpawns on Wave 20 \nA more artistic girl. She likes abstract art and the color red.", sprite : enemy13_spr},
	{title : "Titanium", desc : "175 Health \n2 Speed \nSolid Enemy \n20% Less likely to spawn \nWeighed at 15 points \nSpawns on Wave 21 \nA robotic girl. She likes blowing things up and cutting through things.", sprite : enemy14_spr},
	{title : "Knormle", desc : "35 Health \n4 Speed \n25% More likely to spawn \nWeighed at 9 points \nSpawns on Wave 22 \nAn even less simple girl. She likes parties and cotton candy.", sprite : enemy15_spr},
	//Enemies Page 4
	{title : "Slim Shady", desc : "35 Health \n12 Speed \nCamo Enemy \n15% Less likely to spawn \nWeighed at 15 points \nSpawns on Wave 24 \nA fraudulent girl. She runs for 8 miles every day.", sprite : enemy16_spr},
	{title : "The Real Slim Shady", desc : "75 Health \n10 Speed \Camo Enemy \n30% Less likely to spawn \nWeighed at 30 points \nSpawns on Wave 25 \nA vicious girl. She and the rapper tower have a rivalry.", sprite : enemy17_spr},
	{title : "Gnecromancer", desc : "400 Health \n1 Speed \nSpawns Knormles in groups of 3 every 7 seconds and upon death \n40% Less likely to spawn \nWeighed at 40 points \nSpawns on Wave 26 \nA zombie girl. She likes to read grimdarks in her free time.", sprite : enemy18_spr},
	{title : "Drazy Cave", desc : "80 Health \n-10-30 Speed (Oscillates starting from 10 Speed) \n20% Less likely to spawn \nWeighed at 25 points \nSpawns on Wave 27 \nA very crazy girl. She enjoys tacos, time travelling, and gardening.", sprite : enemy19_spr},
	{title : "Jane Cena", desc : "85 Health \n8 Speed \nInvisible Enemy \n15% Less likely to spawn \nWeighed at 20 points \nSpawns on Wave 28 \nA strong girl. She likes wrestling and not being seen.", sprite : enemy20_spr},
	{title : "Tungsten Cube", desc : "3000 Health \n1 Speed \n50% Less likely to spawn \nWeighed at 35 points \nSpawns on Wave 30 \nA presumably incredibly attractive girl stuck in a cube. Nobody has seen her outside of the cube.", sprite : enemy21_spr},
	{title : "Long Name Girl", desc : "300 Health \n4 Speed \n30% More likely to spawn \nWeighed at 15 points \nSpawns on Wave 31 \nA noble girl. Reports say she can summon lightning that crashes castles in mere seconds.", sprite : enemy22_spr},
	{title : "Dee P.S. Cheque", desc : "500 Health \n8 Speed \nRegenerates 500 Health per second \n75% Less likely to spawn \nWeighed at 35 points \nSpawns on Wave 33 \nThe Gunner's evil twin. Her only negative trait is that she has a terrible work ethic.", sprite : enemy23_spr},
	//Enemies Page 5
	{title : "Glob Moss", desc : "750 Health \n2 Speed \n10% Less likely to spawn \nWeighed at 40 points \nSpawns on Wave 35 \nA mossy girl. She sleeps very often, and uses that energy to create beautiful paintings.", sprite : enemy24_spr},
	{title : "Necrowomancer", desc : "700 Health \n2 Speed \nSpawns Long Name Girls in groups of 5 every 7 seconds and upon death \n35% Less likely to spawn \nWeighed at 70 points \nSpawns on Wave 36 \nA demonic girl. Legends say that she's looking for the mythical girltaker.", sprite : enemy25_spr},
	{title : "You Have Just Lost The Game", desc : "850 Health \n5 Speed \nInvisible, Camo, and Solid Enemy \n25% Less likely to spawn \nWeighed at 35 points \nSpawns on Wave 37 \nA very tricky girl. I think I just lost The Game.", sprite : enemy26_spr},
	{title : "Really Long Name Girl", desc : "6000 Health \n3 Speed \n40% Less likely to spawn \nWeighed at 100 points \nSpawns on Wave 39 \nA girl of battle. She fights passionately for the one true Evil Girl.", sprite : enemy27_spr},
	{title : "Final Foss", desc : "25 Health \n2 Speed \nSpawns on Stage 1 \nA slimy woman. She thinks very highly of herself, but doesn't know that she's actually the first boss to appear.", sprite : enemy28_spr},
	{title : "Negative Nancy", desc : "67>100>187>200 Health \n2 Speed \nSpawns on Stages 2-5 \nAn even slimier woman. Despite her name, she's actually a very sweet person.", sprite : enemy29_spr},
	{title : "Ferocious Female", desc : "175>250>275>325>450 Health \n3 Speed \nGains Camo from Stage 8 to 10. \nSpawns on Stages 6-10 \nA murderous woman. She paints with blood, like straight up. It doesn't make for a very interesting piece.", sprite : enemy30_spr},
	{title : "Destructive Damsel", desc : "750>1250>2000>3000>4500 Health \n2 Speed \nSolid Boss \nSpawns on Stages 11-15 \nA rogue android woman. She used to sing alongside the Debt Collector, but an argument about what the best fruit was made them bitter rivals.", sprite : enemy31_spr},
	//Enemies Page 6
	{title : "Malicious Madam", desc : "5000>6000>7500 Health \n2 Speed \nGains Camo in Stage 17, exchanged for Invisibility in Stage 18 \nSpawns on Stages 16-18 \nA punctual woman. She was formerly the Commander for Girls United when the Spanish AIDS attacked, but now acts as Commander's evil counterpart.", sprite : enemy32_spr},
	{title : "Your Mother", desc : "25000 Health \n1 Speed \nSpawns on Stage 19 \nAn entitled woman. She wanted her daughter to be the Cheerleader for Girls United, but was rejected on the grounds of her daughter incredibly mean.", sprite : enemy33_spr},
	{title : "Evil Girl", desc : "75000 Health \n1 Speed \nThe ultimate boss Spawns on every stage after 19. \nThe most evil girl. She sits upon her living throne to establish dominance over you and your towers. Most likely caused the Spanish AIDS outbreak.", sprite : enemy34_spr},
	{title : "The Meadows", desc : "The meadows of the continent were the hardest to take from our hands due to their proximity to decent civilization. Very fortunately, they overstretched their supply lines at this point, making it easy to push against their tyranny. \nThe simple, easily defendable paths of the meadows are incredible places to resist the onslaught of evil girls.", sprite : enemy0_spr},
	{title : "The Dunes", desc : "When the evil girls arrived at the dunes, the heat made it difficult to support larger invasions, yet the unforgiving desert also made it hard to stop them. \nAs we fight back against the invaders, one can only wonder why they decided to make the dunes such an important area.", sprite : enemy5_spr},
	{title : "The Pits", desc : "Caves and underground bunkers were the easiest places to seize for Evil Girls United, which makes reclaiming them all the worse for us. \nThese places are usually where evil girls are produced en masse, as their isolation from decent civilization is perfect for the creation process.", sprite : enemy10_spr},
	{title : "End of the Line", desc : "The outskirts of the continent, where hermits and nomads lived, were the first to be taken by Evil Girls United. The hostile environment of these places are perfect for cloning the most powerful evil girls, creating the most difficult hordes to fight off. \nDespite this, your resilience will be key to bringing down Evil Girls United once and for all.", sprite : enemy15_spr},
	{title : "Epilogue", desc : "If you're seeing this, congratulations! You're one of our most talented operators in all of Girls United. Despite the odds, you managed to hold your own against Evil Girls United using your own senses and resources. Here's a medallion for you, Now get the heck outta here!", sprite : enemy20_spr},
	//Tier 4s Page 1
	{title : "Soldier", desc : "Tier 4 gunner \nChanges bullet pierce from 1 >> 2 \nAttack Speed 21 >> 30 \nDamage 1 >> 3 \nRange 250 >> 350", sprite : tower16_spr, spriteShooting : towerShooting16_spr},
	{title : "Assassin", desc : "Tier 4 Sniper \nDamage 7 >> 14 \nFirerate 90 >> 120 \nRange 500 >> 600 \nEach consecutive hit on one enemy makes the sniper do an additional +20% damage up to 400% damage.", sprite : tower17_spr, spriteShooting : towerShooting17_spr},
	{title : "Gauss Machine Gun", desc : "Tier 4 Railgunner \nDamage 75 >> 80 \nFirerate 5 sec. >> 10 sec. \nPierce 20 >> 30 \nShoots out a burst of high energy beams for 1 second (1 shot every 0.1 frames for 800 damage total)", sprite : tower18_spr, spriteShooting : towerShooting18_spr},
	{title : "Dissapator", desc : "Tier 4 Evaporator \Damage: 1000 >> 2500 \Range: 400 >> 500 \Pierce: 1 >> 50 \Cooldown: 10 sec. >> 20 sec. \nCreates an explosion upon impact", sprite : tower19_spr, spriteShooting : towerShooting19_spr}]
	//Tier 4s Page 2
	//Modifiers Page 1
	//Modofiers Page 2
	//Modifiers Page 3
	//Modofiers Page 4