image_alpha = 1

if (global.autostart) {
	image_index = 1
}

adjusting = false
goUp = true
alarmList = []

showDisplay = -1
frame = 0
shooting = false
page = 0
modifierTranslations = ["Time Waster", "Chonker", "Wheel", "We are running out of money to buy you all beans", "Scammed", "Legal Issues", "No House Insurance", "UltraScitzo", "Bruh you slow af", "Bruh you weak af", "They messed up my prescription", "Negative Reinforcement", "You play well, but can you tango with 2?", "Big and Burly", "Inflation", "Awful Game Design", "The Moon", "The Sun", "Death", "The Fool", "The Magician", "The High Priestess", "Empress", "Temperance", "Fortune Teller", "The Wheel of Fortune", "Judgement", "Strength", "The World", "The Tower"]
logbookEntries = ["Gunner", "Sniper", "Railgunner", "Evaporator", "Boomer", "Flamer", "Puncher", "Laser", "Cheerleader", "Moneymaker", "Spotter", "Booster", "Commander", "Hacker", "Rapper", "Debt Collector", "Normal Enemies", "Camo Enemies", "Solid Enemies", "Invisible Enemies", "", "", "", "", "Soldier"]
logbookDesc = [{title : "Gunner", desc : "Cheap, simple tower with consistent damage. \n$150 \n1 Damage \n0.5 sec Cooldown \n250 range \nUpgrade costs $75 >> $125 >> $200 >> $550", sprite : tower0_spr, spriteShooting : towerShooting0_spr},
	{title : "Sniper", desc : "Slightly more expensive tower with high damage and lower firerate. \n$325 \n7 Damage \n2 sec Cooldown \n500 range \nAutomatic camo detection \nUpgrade costs $125 >> $200 >> $325 >> $850", sprite : tower1_spr, spriteShooting : towerShooting1_spr},
	{title : "Railgunner", desc : "Expensive tower with very low firerate and very high damage. \n$1000 \n75 Damage \n5 sec Cooldown \n550 range \n20 Pierce \nAutomatic camo detection \nUpgrade costs $500 >> $825 >> $1300 >> $4800", sprite : tower2_spr, spriteShooting : towerShooting2_spr},
	{title : "Evaporator", desc : "Boss killer tower with AOE damage at higher levels, highest damage. \n$3750 \n1000 Damage \n10 sec Cooldown \n400 range \nHas invisible detection \nUpgrade costs $1750 >> $2750 >> $4500 >> $14000", sprite : tower3_spr, spriteShooting : towerShooting3_spr},
	{title : "Boomer", desc : "Low cost, low damage AOE tower that deals better chip damage at later levels. \n$200 \n2 Damage \n1 sec Cooldown \n200 range \n10 Pierce \nCan hit solids \nUpgrade costs $100 >> $150 >> $275 >> $650", sprite : tower4_spr, spriteShooting : towerShooting4_spr},
	{title : "Flamer", desc : "Pricier tower that sets enemies on fire which turns them into sludge. \n$550 \n0.2 Damage \n0.5 sec Cooldown \n150 range \nCan hit solids \nSets enemies on fire that does 10 damage over 3.3 seconds \nUpgrade costs $275 >> $450 >> $725 >> $1500", sprite : tower5_spr, spriteShooting : towerShooting5_spr},
	{title : "Puncher", desc : "Pricier tower that hits multiple enemies with their swings for higher damage mutli target. \n$1000 \n5 Damage \n0.5 sec Cooldown \n5 Pierce \n100 range \nUpgrade costs $500 >> $825 >> $1325 >> $4250", sprite : tower6_spr, spriteShooting : towerShooting6_1_spr},
	{title : "Laser", desc : "Expensive tower that covers an entire line of the map to shred enemies. \n$5000 \n3 Damage \n0.2 sec Cooldown \n25 Pierce \nFires a continuous beam that doesn't rotate \nUpgrade costs $2500 >> $4150 >> $6500 >> $8000", sprite : tower7_spr},
	{title : "Cheerleader", desc : "Support tower that encourages others and boosts firerate. \n$850 \n10% firerate buff \nrange 300 \nUpgrade Costs $425 >> $700 >> $1125 >> $2000", sprite : tower8_spr},
	{title : "Moneymaker", desc : "Pricier support tower that makes good financial decisions during the round for money. \n$700 \n$100 per wave \nUpgrade Costs $350 >> $575 >> $925 >> $1800", sprite : tower9_spr},
	{title : "Spotter", desc : "Even pricier support tower that gives tips on the weak-points of enemies and tells other towers where to shoot. \n$1500 \nrange 450 \n+10% damage \n+15% range \nGives Camo Detection \nUpgrade Costs $1750 >> $2850 >> $3500 >> $5500", sprite : tower10_spr},
	{title : "Booster", desc : "Definitive support tower that increases the damage of other girls. \n$2400 \nrange 350 \nstarts with 40% damage boost ability that give to 1 tower in range \nUpgrade Costs $2000 >> $3250 >> $5350 >>$7000", sprite : tower11_spr},
	{title : "Commander", desc : "All-in-one tower that calls in strategic bomb placements according to their targeting. She also boosts the firerate of the other towers. \n$3500 \nMultiple aerial attacks every 600 or so frames which focus on a place on the path (each bomb does 50 damage). \nif set on strongest the bombs will all focus on one target \n+15% attack speed \nCamo and lead hitting \nUpgrade Costs $2000 >> $3250 >> $5250 >> $10000", sprite : tower12_spr},
	{title : "Hacker", desc : "Tower that gives a discount on upgrading girls. She also has multiple beams which can focus into one to shred a single target. \n$3500 \n5% discount \n2 beams that focus onto enemies (5 damage every 12 frames for 25 dps) \n450 range \nInvisible detection, lead detection, and camo detection \nUpgrade Costs $1875 >> $3125 >> $5000 >> $8000", sprite : tower13_spr, spriteShooting : towerShooting13_spr},
	{title : "Rapper", desc : "A tower similar to moneymaker that uses their piercing bars to beat up enemies. \n$1700 \nMakes $250 \nPuncher-esque attack every 0.2 seconds for 5 damage. \nInvisibility detection \nPierce 5 \nUpgrade Costs $1750 >> $2900 >> $4650 >> $10000", sprite : tower14_spr, spriteShooting : towerShooting14_spr},
	{title : "Debt Collector", desc : "A tower that can't be upgraded, but gets more powerful the more enemies they beat up. \n$800 \nLevels up at 10 enemies, 50 enemies, and 250 enemies. \nEach additional kill after 250 enemies gives an extra +0.2% damage \nUses a shotgun that shoots pellets 3 >> 5 >> 7 >> 10 with a 15 degree spread on each side \nDamage 2 >> 5 >> 10 >> 25 \nFirerate 60 >> 45 >>  >> 12 \nRange 250 >> 300 >> 450 >> 650 \nGives extra money from enemies. Bonus cash scales from: +0% >> +25% >> +50% >> +100% \nNo detections >> Camo detection>>camo + lead detection>>invisibility + camo + lead detection", sprite : tower15_spr, spriteShooting : towerShooting15_spr},
	{title : "Normal Enemies", desc : "Enemies follow the path as normal, take 100% damage, and do not have any resistances.", sprite : enemy0_spr},
	{title : "Camo Enemies", desc : "Camo enemies can only be spotted by towers that have camo detection, however, if a camo enemy is caught in an explosion they will also take full damage from it", sprite : enemy4_spr},
	{title : "Solid Enemies", desc : "Solid enemies take -75% damage or only 1/4th the normal amount from regular towers, but any tower with the ability to pierce solids will do the full 100% damage.", sprite : enemy5_spr},
	{title : "Invisible Enemies", desc : "Invisible enemies can't be hit by towers with no detections. Towers with either camo or solid hitting do -75% damage to invisible enemies. Towers will both camo and solid htting do 50% damage, and towers with invisibility detection will always do 100% damage, no matter the other detections. Towers with only invisibility detection do not gain camo or solid hitting.", sprite : enemy9_spr}]